name: Update Repo

on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Repositories and Install Dependencies
      run: |
        sudo apt update
        sudo apt install git
        
    - name: Retrieve JHU CSSE Data
      run: git clone https://github.com/CSSEGISandData/COVID-19.git
    
    - name: Modify Repository
      run: cd COVID-19/csse_covid_19_data/csse_covid_19_daily_reports ; mv `date "+%m-%d-%Y" -d "2 day ago"`".csv" ../../../currentreport.csv
        
    - name: Push Changes 
      run: cd .github/workflows/ ; chmod +x commit.sh ; ./commit.sh ${GITHUB_REF##*/} `date "+%m-%d-%Y" -d "2 day ago"`
    
    - name: Unrelated - Maintain Fileshare Validity
      run: |
        wget https://srv-store2.gofile.io/download/924Imd/still_Image.png
        wget https://srv-store2.gofile.io/download/924Imd/animationA.gif
        wget https://srv-store2.gofile.io/download/924Imd/animations.nb
        wget https://srv-store2.gofile.io/download/924Imd/animations.pdf
        wget https://srv-store2.gofile.io/download/924Imd/still_Image.pdf
